<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Order;
use App\Models\User;
use Illuminate\Support\Str;

class ProcessedOrdersSeeder extends Seeder
{
    public function run(): void
    {
        // Get the first user (or create one if none exists)
        $user = User::first();
        if (!$user) {
            $user = User::create([
                'name' => 'Demo User',
                'email' => 'demo@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
            ]);
        }

        // Create sample processed orders with different statuses
        $orders = [
            [
                'customer_name' => 'Lakpa Sherpa',
                'customer_phone' => '9851277908',
                'shipping_address' => 'KATHMANDU',
                'payment_method' => 'cash_on_delivery',
                'total_amount' => 180,
                'order_number' => 'ORD-0028',
                'status' => 'processing',
                'payment_status' => 'unpaid',
            ],
            [
                'customer_name' => 'Karna Khadka',
                'customer_phone' => '9841893622',
                'shipping_address' => 'POKHARA',
                'payment_method' => 'cash_on_delivery',
                'total_amount' => 120.18,
                'order_number' => 'ORD-0027',
                'status' => 'completed',
                'payment_status' => 'unpaid',
            ],
            [
                'customer_name' => 'Sunil Tyata',
                'customer_phone' => '9851234567',
                'shipping_address' => 'LALITPUR',
                'payment_method' => 'paid',
                'total_amount' => 250,
                'order_number' => 'ORD-0026',
                'status' => 'shipped',
                'payment_status' => 'paid',
            ],
            [
                'customer_name' => 'Bishnu Prasad',
                'customer_phone' => '9842345678',
                'shipping_address' => 'BHAKTAPUR',
                'payment_method' => 'cash_on_delivery',
                'total_amount' => 150,
                'order_number' => 'ORD-0025',
                'status' => 'confirmed',
                'payment_status' => 'unpaid',
            ],
            [
                'customer_name' => 'Sita Devi',
                'customer_phone' => '9853456789',
                'shipping_address' => 'KATHMANDU',
                'payment_method' => 'cash_on_delivery',
                'total_amount' => 300,
                'order_number' => 'ORD-0024',
                'status' => 'cancelled',
                'payment_status' => 'unpaid',
            ],
            [
                'customer_name' => 'Ram Bahadur',
                'customer_phone' => '9844567890',
                'shipping_address' => 'CHITWAN',
                'payment_method' => 'paid',
                'total_amount' => 175,
                'order_number' => 'ORD-0023',
                'status' => 'completed',
                'payment_status' => 'paid',
            ],
            [
                'customer_name' => 'Gita Kumari',
                'customer_phone' => '9855678901',
                'shipping_address' => 'POKHARA',
                'payment_method' => 'cash_on_delivery',
                'total_amount' => 220,
                'order_number' => 'ORD-0022',
                'status' => 'processing',
                'payment_status' => 'unpaid',
            ],
            [
                'customer_name' => 'Hari Prasad',
                'customer_phone' => '9846789012',
                'shipping_address' => 'BUTWAL',
                'payment_method' => 'cash_on_delivery',
                'total_amount' => 195,
                'order_number' => 'ORD-0021',
                'status' => 'shipped',
                'payment_status' => 'unpaid',
            ],
            [
                'customer_name' => 'Maya Devi',
                'customer_phone' => '9857890123',
                'shipping_address' => 'DANG',
                'payment_method' => 'paid',
                'total_amount' => 280,
                'order_number' => 'ORD-0020',
                'status' => 'completed',
                'payment_status' => 'paid',
            ],
            [
                'customer_name' => 'Krishna Bahadur',
                'customer_phone' => '9848901234',
                'shipping_address' => 'SURKHET',
                'payment_method' => 'cash_on_delivery',
                'total_amount' => 160,
                'order_number' => 'ORD-0019',
                'status' => 'cancelled',
                'payment_status' => 'unpaid',
            ],
            [
                'customer_name' => 'Laxmi Kumari',
                'customer_phone' => '9859012345',
                'shipping_address' => 'KATHMANDU',
                'payment_method' => 'paid',
                'total_amount' => 340,
                'order_number' => 'ORD-0018',
                'status' => 'confirmed',
                'payment_status' => 'paid',
            ],
            [
                'customer_name' => 'Suresh Thapa',
                'customer_phone' => '9840123456',
                'shipping_address' => 'POKHARA',
                'payment_method' => 'cash_on_delivery',
                'total_amount' => 210,
                'order_number' => 'ORD-0017',
                'status' => 'processing',
                'payment_status' => 'unpaid',
            ],
            [
                'customer_name' => 'Kamala Devi',
                'customer_phone' => '9851234567',
                'shipping_address' => 'LALITPUR',
                'payment_method' => 'cash_on_delivery',
                'total_amount' => 185,
                'order_number' => 'ORD-0016',
                'status' => 'completed',
                'payment_status' => 'unpaid',
            ],
            [
                'customer_name' => 'Bhim Prasad',
                'customer_phone' => '9842345678',
                'shipping_address' => 'BHAKTAPUR',
                'payment_method' => 'paid',
                'total_amount' => 265,
                'order_number' => 'ORD-0015',
                'status' => 'shipped',
                'payment_status' => 'paid',
            ],
            [
                'customer_name' => 'Sangita Kumari',
                'customer_phone' => '9853456789',
                'shipping_address' => 'CHITWAN',
                'payment_method' => 'cash_on_delivery',
                'total_amount' => 145,
                'order_number' => 'ORD-0014',
                'status' => 'cancelled',
                'payment_status' => 'unpaid',
            ],
            [
                'customer_name' => 'Tek Bahadur',
                'customer_phone' => '9844567890',
                'shipping_address' => 'KATHMANDU',
                'payment_method' => 'cash_on_delivery',
                'total_amount' => 320,
                'order_number' => 'ORD-0013',
                'status' => 'confirmed',
                'payment_status' => 'unpaid',
            ],
            [
                'customer_name' => 'Radha Devi',
                'customer_phone' => '9855678901',
                'shipping_address' => 'POKHARA',
                'payment_method' => 'paid',
                'total_amount' => 195,
                'order_number' => 'ORD-0012',
                'status' => 'processing',
                'payment_status' => 'paid',
            ],
            [
                'customer_name' => 'Narayan Prasad',
                'customer_phone' => '9846789012',
                'shipping_address' => 'BUTWAL',
                'payment_method' => 'cash_on_delivery',
                'total_amount' => 275,
                'order_number' => 'ORD-0011',
                'status' => 'completed',
                'payment_status' => 'unpaid',
            ],
            [
                'customer_name' => 'Ganga Devi',
                'customer_phone' => '9857890123',
                'shipping_address' => 'DANG',
                'payment_method' => 'paid',
                'total_amount' => 155,
                'order_number' => 'ORD-0010',
                'status' => 'shipped',
                'payment_status' => 'paid',
            ],
            [
                'customer_name' => 'Yam Bahadur',
                'customer_phone' => '9848901234',
                'shipping_address' => 'SURKHET',
                'payment_method' => 'cash_on_delivery',
                'total_amount' => 230,
                'order_number' => 'ORD-0009',
                'status' => 'cancelled',
                'payment_status' => 'unpaid',
            ],
            [
                'customer_name' => 'Durga Kumari',
                'customer_phone' => '9859012345',
                'shipping_address' => 'KATHMANDU',
                'payment_method' => 'paid',
                'total_amount' => 290,
                'order_number' => 'ORD-0008',
                'status' => 'confirmed',
                'payment_status' => 'paid',
            ],
            [
                'customer_name' => 'Shyam Prasad',
                'customer_phone' => '9840123456',
                'shipping_address' => 'LALITPUR',
                'payment_method' => 'cash_on_delivery',
                'total_amount' => 170,
                'order_number' => 'ORD-0007',
                'status' => 'processing',
                'payment_status' => 'unpaid',
            ],
            [
                'customer_name' => 'Parbati Devi',
                'customer_phone' => '9851234567',
                'shipping_address' => 'BHAKTAPUR',
                'payment_method' => 'cash_on_delivery',
                'total_amount' => 245,
                'order_number' => 'ORD-0006',
                'status' => 'completed',
                'payment_status' => 'unpaid',
            ],
            [
                'customer_name' => 'Kedar Bahadur',
                'customer_phone' => '9842345678',
                'shipping_address' => 'CHITWAN',
                'payment_method' => 'paid',
                'total_amount' => 315,
                'order_number' => 'ORD-0005',
                'status' => 'shipped',
                'payment_status' => 'paid',
            ],
            [
                'customer_name' => 'Saraswati Kumari',
                'customer_phone' => '9853456789',
                'shipping_address' => 'POKHARA',
                'payment_method' => 'cash_on_delivery',
                'total_amount' => 135,
                'order_number' => 'ORD-0004',
                'status' => 'cancelled',
                'payment_status' => 'unpaid',
            ],
            [
                'customer_name' => 'Mohan Prasad',
                'customer_phone' => '9844567890',
                'shipping_address' => 'BUTWAL',
                'payment_method' => 'paid',
                'total_amount' => 285,
                'order_number' => 'ORD-0003',
                'status' => 'confirmed',
                'payment_status' => 'paid',
            ],
            [
                'customer_name' => 'Kumari Devi',
                'customer_phone' => '9855678901',
                'shipping_address' => 'DANG',
                'payment_method' => 'cash_on_delivery',
                'total_amount' => 200,
                'order_number' => 'ORD-0002',
                'status' => 'processing',
                'payment_status' => 'unpaid',
            ],
            [
                'customer_name' => 'Bikram Thapa',
                'customer_phone' => '9846789012',
                'shipping_address' => 'SURKHET',
                'payment_method' => 'paid',
                'total_amount' => 255,
                'order_number' => 'ORD-0001',
                'status' => 'completed',
                'payment_status' => 'paid',
            ],
        ];

        foreach ($orders as $orderData) {
            Order::create([
                'user_id' => $user->id,
                'order_number' => $orderData['order_number'],
                'subtotal' => $orderData['total_amount'],
                'tax' => 0,
                'shipping' => 0,
                'total' => $orderData['total_amount'],
                'status' => $orderData['status'],
                'payment_status' => $orderData['payment_status'],
                'payment_method' => $orderData['payment_method'],
                'shipping_address' => $orderData['shipping_address'],
                'notes' => 'Processed order',
                'is_manual' => false,
                'created_by' => 1, // Assuming admin user ID is 1
                'created_at' => now()->subDays(rand(1, 30)),
                'updated_at' => now()->subDays(rand(1, 30)),
            ]);
        }

        $this->command->info('Sample processed orders created successfully!');
    }
}